### ISSUE TITLE
Expired sales tax rates served (from 2023)

### ISSUE THREAD

**Issue by danry25** [uncheckederror/WASalesTaxLookup#3]
It looks like the tax rate being served is only valid through 2023.

![image](https://github.com/uncheckederror/WASalesTaxLookup/assets/1683673/3b946ebc-0e8a-436c-a954-78f965881c5b)

**Comment by uncheckederror** [comment]
@danry25 this issue appears to be resolved now: 
![image](https://github.com/uncheckederror/WASalesTaxLookup/assets/11726956/406f9933-9b0f-41e7-8bc4-160ca9b432b1)
